name        : groff
version     : 1.22.2
release     : 1
source      :
    - ftp://ftp.gnu.org/gnu/groff/groff-1.22.2.tar.gz : 380864dac4772e0c0d7b1282d25d0c5fd7f63baf45c87c4657afed22a13d2076
homepage    : http://www.gnu.org/software/groff
license     : GPL-3.0+
summary     : groff (Typesetting package to read formatted files)
component   : desktop.base
description : |
    groff (GNU troff) is a typesetting package which reads plain text mixed with formatting commands and produces formatted output
patterns   :
    - docs: /usr/share/doc/*
setup      : |
    %configure --prefix=/usr \
               --with-awk=/usr/bin/awk \
               --with-gnu-ld \
               --without-x
build      : |
    %make
install    : |
    %make_install
    ln -s eqn %installroot%/usr/bin/geqn
    ln -s tbl %installroot%/usr/bin/gtbl
