name       : groff
version    : 1.22.4
release    : 3
source     :
    - https://mirrors.rit.edu/gnu/groff/groff-1.22.4.tar.gz : e78e7b4cb7dec310849004fa88847c44701e8d133b5d4c13057d876c1bad0293
homepage   : http://www.gnu.org/software/groff
license    : GPL-3.0-or-later
summary    : groff (Typesetting package to read formatted files)
component  : desktop.base
description: |
    groff (GNU troff) is a typesetting package which reads plain text mixed with formatting commands and produces formatted output
patterns   :
    - docs : /usr/share/doc/*
setup      : |
    %configure --prefix=/usr \
               --with-awk=/usr/bin/awk \
               --with-gnu-ld \
               --without-x
build      : |
    %make
install    : |
    %make_install
    ln -s eqn %installroot%/usr/bin/geqn
    ln -s tbl %installroot%/usr/bin/gtbl
